// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWceqTLSeetdcE3u69xrxB9R8oQKcqgk',
    appId: '1:189200921211:web:2bf2dbd8ddad104adf28de',
    messagingSenderId: '189200921211',
    projectId: 'controledeabastecimento-7acdf',
    authDomain: 'controledeabastecimento-7acdf.firebaseapp.com',
    storageBucket: 'controledeabastecimento-7acdf.firebasestorage.app',
    measurementId: 'G-BF4N4Q707C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu8mgquNj3ila6GFBa7IisaNC53B5xQGI',
    appId: '1:189200921211:android:b95fe919ea470833df28de',
    messagingSenderId: '189200921211',
    projectId: 'controledeabastecimento-7acdf',
    storageBucket: 'controledeabastecimento-7acdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2tBScJu4IcvjaL4fGwV4yUQqbRf7Wgg',
    appId: '1:189200921211:ios:f3c4078ff9768c14df28de',
    messagingSenderId: '189200921211',
    projectId: 'controledeabastecimento-7acdf',
    storageBucket: 'controledeabastecimento-7acdf.firebasestorage.app',
    iosBundleId: 'com.example.controleDeAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj2tBScJu4IcvjaL4fGwV4yUQqbRf7Wgg',
    appId: '1:189200921211:ios:f3c4078ff9768c14df28de',
    messagingSenderId: '189200921211',
    projectId: 'controledeabastecimento-7acdf',
    storageBucket: 'controledeabastecimento-7acdf.firebasestorage.app',
    iosBundleId: 'com.example.controleDeAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWceqTLSeetdcE3u69xrxB9R8oQKcqgk',
    appId: '1:189200921211:web:50d708243ba7b1f6df28de',
    messagingSenderId: '189200921211',
    projectId: 'controledeabastecimento-7acdf',
    authDomain: 'controledeabastecimento-7acdf.firebaseapp.com',
    storageBucket: 'controledeabastecimento-7acdf.firebasestorage.app',
    measurementId: 'G-FW79MSN2BL',
  );
}
